### ISSUE TITLE
如何利用stroyboard实现tableviewcontroller的加载

### ISSUE THREAD

**Issue by ddcfcs** [yyued/TwitterPaggingViewer#1]
首先我利用
XHTableViewController *tableViewController = [mainStoryboard instantiateViewControllerWithIdentifier:@"XHTVC"]取得了sb上的tvc，
然后想在XHTwitterPaggingViewer的数组属性里加入刚才取得的tvc，运行程序时候发现无法执行到XHTableViewController的m文件，为何啊？

**Comment by xhzengAIB** [comment]
Hi! @ddcfcs
我不是很明白你的意思，如果你是想使用该组件的功能，那你得知道，你需要哪块功能，比如你只需要展示页面，展示的内容页面是用SB上初始化得到的。

**Comment by xhzengAIB** [comment]
我说几个点吧！

1、你想要展示功能
2、你想要展示功能，而且能绑定某个页面是SB的控制器
3、如果你想要全部功能，我得写demo，

**Comment by ddcfcs** [comment]
好吧，我梳理一下
1.我先在SB上添加了一个UIViewController，然后Embed in一个UINavigationController；
2.在这个UIViewController上使用你的那个XHTableViewController（这个tvb实现了动态加载图片和title，就是答主展示的样子）；
3，运行程序发现不能显示XHTableViewController

通过打断点发现没用运行到XHTableViewController.m里，为何会这样子？

**Comment by PonyCui** [comment]
需要明确sb中是否已经继承正确

发自我的 iPhone

**Comment by ddcfcs** [comment]
什么意思啊？

**Comment by xhzengAIB** [comment]
意思是让你确认SB里面的class是否对应写对了，不过我大概明白你的需求了，意思你想用SB来做界面，我大概可以写一个demo

**Comment by ddcfcs** [comment]
对的啊，我单独运行XHTableViewController 时（就是把SB的开始箭头放到XHTableViewController上 ）可以显示的

**Comment by xhzengAIB** [comment]
Hi！@ddcfcs @flymwy 

算是解决了，但是你会发现没有UITabBarController那么好用，在SB的情况下，我问问崔神是否有好的办法。

可以看这个commit：https://github.com/duowan/TwitterPaggingViewer/commit/68b2a4ffce068dafc80d4a4778f1f1eb6839a3e2

Jack

**Comment by ddcfcs** [comment]
1.根据答主的提示，我在AppDelegate里运行的是这个代码
    UINavigationController _navigationController = (UINavigationController *)self.window.rootViewController;
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main_iPhone" bundle:nil];
    XHTableViewController *tableViewController1 = [storyboard instantiateViewControllerWithIdentifier:@"XHTVC"];
    tableViewController1.title = @"Home";
    UIViewController *viewcontroller = (UIViewController *)navigationController.topViewController;
    [viewcontroller addChildViewController:tableViewController1];
运行没有显示TVC
2.  我又放在UINavigationController 里的uiviewcontroller的viewDidLoad里，
    UIStoryboard_ mainStoryboard = [UIStoryboard storyboardWithName:@"Main_iPhone" bundle:nil];
    XHTableViewController *tableViewController = [mainStoryboard instantiateViewControllerWithIdentifier:@"XHTVC"];
    [self addChildViewController:tableViewController];
意思就是在这里加载上SB里的TVC，为什么运行还是会没效果呢

**Comment by xhzengAIB** [comment]
@ddcfcs 
其实你应该要知道  addChildViewController方法的作用，你的view呢？add了吗？

**Comment by ddcfcs** [comment]
原来如此阿，多谢
