### ISSUE TITLE
请问这个初始化带有左右滑动菜单的Viewer控制器什么意思啊

### ISSUE THREAD

**Issue by ddcfcs** [yyued/TwitterPaggingViewer#2]
看demo上没有什么：左边／右边滑动菜单的viewer控制器啊？
initWithLeftViewControlle也没有调用，不太明白是要做出什么效果？

**Comment by xhzengAIB** [comment]
您好！
左右侧滑菜单，用于显示一些menu的操作，这个看你们的需求吧！

Jack

**Comment by xhzengAIB** [comment]
可以先保留这个issue

**Comment by ddcfcs** [comment]
还有个问题，didChangedPageCompleted这个回调函数貌似只看到了使用，并没有写具体的实现把

**Comment by xhzengAIB** [comment]
这个block只是用于回调，在外部实现的，当你改变页面的时候，需要通知到外部

**Comment by ddcfcs** [comment]
那个pageviewcontroler内添加TVC的话，是不是必须加UIScrollView（我使用的是SB生成的TVC，是不是有什么设置可以直接识别滑动手势）？
因为我发现，如果我在pageviewcontroler内添加普通的UIViewController的话，是可以左右滑动的。
