### ISSUE TITLE
Start from the second view controller: 您好，您可以通过2的ViewController开始？

### ISSUE THREAD

**Issue by zoelounge** [yyued/TwitterPaggingViewer#4]
Hello,
thank you for your work.
how can I start from the second view controller?
Thx.
嗨，谢谢你的工作
我怎么能在第二的ViewController开始？ 
谢谢

**Comment by xhzengAIB** [comment]
这个可以有，我找个时间给你做吧！最近有点忙

**Comment by zoelounge** [comment]
感谢您的时间。你很善良

我尝试了一些解决办法，但我找到了合适的人。

**Comment by zoelounge** [comment]
请原谅我的中国，我翻译与谷歌翻译，我宁愿说英语。

**Comment by xhzengAIB** [comment]
你看我提交的commit吧
