### ISSUE TITLE
Method to go directly in a specific page

### ISSUE THREAD

**Issue by Piero87** [yyued/TwitterPaggingViewer#7]
Hello,
it's possible have a method to go directly in a specific page?

**Comment by xhzengAIB** [comment]
@Piero87 
yet! i will add this method on open source lib

Jack

**Comment by xhzengAIB** [comment]
https://github.com/duowan/TwitterPaggingViewer/blob/master/XHTwitterPaggingViewer/XHTwitterPaggingViewer.h#L68
