### ISSUE TITLE
How to add Navigation bar button item when use your code in project.

### ISSUE THREAD

**Issue by nitingohel** [yyued/TwitterPaggingViewer#9]
i used your code in one of the my project your are done good job but i get an issue like i can not see my view-controller Bar-button item:
![screen shot 2014-11-06 at 12 23 02 pm](https://cloud.githubusercontent.com/assets/5137595/4931945/b6f8cd38-6581-11e4-99fa-81260ab30f79.png)

and output is:

![screen shot 2014-11-06 at 12 23 28 pm](https://cloud.githubusercontent.com/assets/5137595/4931948/bdb64f2e-6581-11e4-843d-cee3de4b438c.png)

**Comment by xhzengAIB** [comment]
yet! got it, 
You need push barButtonItem in window.rootViewController ViewDidLoad method，if you window.rootViewController is navigationController, now push this code to navigationController.rootViewController ViewDidLoad method. 

What I mean is need in the navigation controller with the controller on the operation

Jack

**Comment by nitingohel** [comment]
Thank you for fast reply Jack.  actuly i used tab-bar controller at the click on login button i create a tabbarcontroller and in first tab i used this twitpaggination code my login click event code is following:

![screen shot 2014-11-06 at 12 53 59 pm](https://cloud.githubusercontent.com/assets/5137595/4932189/ecce3a5c-6585-11e4-8a5f-a8194746df3c.png)

**Comment by xhzengAIB** [comment]
@nitingohel 
Using tabBarController in to you app, i create a demo show you.

**Comment by nitingohel** [comment]
thank you mate please add bar button item in to your demo so i can understand well. thanks for your support. and give me link when you update your demo.

**Comment by xhzengAIB** [comment]
look this demo (https://github.com/duowan/TwitterPaggingViewer/tree/master/Example/XHTwitterPaggingViewerStoryboradExample)

Jack

**Comment by nitingohel** [comment]
thank you mate but demoviewcontroller is not a viewcontrolelr that added in paging so that + button action in demoviewcontroller and we are adding view controller in paging is tableviewcontroller. :( what how does that helpful?
